refactor: use whiskers
catppuccin/sc-im pull request #1
Opened 2024-05-28 14:50 UTC by uncenter

Adds [Whiskers](https://github.com/catppuccin/toolbox/tree/main/whiskers) to build the themes. Instead of the shell build script, edit the `sc-im.tera` file and then run `just build` to build the output themes. You will need Whiskers (linked above) and *optionally* [Just](https://github.com/casey/just) installed.

2024-05-30 22:43 UTC, uncenter commented on dist/frappe
I can make it so that the `REDEFINE_COLOR`s are all at the top though I think it is a lot of unnecessary complexity.

2024-06-10 22:06 UTC, sgoudham requested changes

2024-06-10 22:06 UTC, sgoudham commented on dist/frappe
> +DEFINE_COLOR   "GREEN"     166 209 137
`GREEN` changes from `REDEFINE_COLOR` to `DEFINE_COLOR` ?

2024-06-14 20:30 UTC, sgoudham approved these changes

2024-06-14 20:30 UTC, merged